eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    non-secure-port: {server.port}
server:
  port: 8082